package com.store.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pessoa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Código")
	private int codigo;
	@org.kie.api.definition.type.Label(value = "Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;
	
	private static int counter = 1;

	public Pessoa() {
	    this.codigo = counter++;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = this.codigo;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Pessoa(int codigo, java.lang.String nome, java.lang.String status) {
		this.codigo = codigo;
		this.nome = nome;
		this.status = status;
	}

}